- name: Run data_fetcher
  run: python src/data_fetcher.py  # カレントディレクトリ=リポジトリルート

- name: Debug listing
  run: ls -la

- name: Commit and push
  run: |
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add sheet_query_data.csv
    git commit -m "chore: update CSV at $(date +'%Y-%m-%d %H:%M:%S')"
    git push
